name: blog DEPLOY CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  publish_packages_job:
    runs-on: ubuntu-latest
    name: build
    steps:
      # check out the repository
      - name: Checkout    
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Change this to the Node.js version you're using
          registry-url: 'https://npm.pkg.github.com'
          scope: '@databendcloud'  # Change this to your GitHub organization or username

      - name: Install and Build 
        run: yarn

      - name: get fetch
        run: npm run fetch

      - name: generate
        run: |
          npm run generate
          npm run build
          npm run build:bundle

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}


      - name: Publish to npm registry
      run: |
        echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_DATABEND_TOKEN_NPM_OUT }}
        
      # - name: Publish
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      # - name: Pushes to another repository
      #   uses: cpina/github-action-push-to-another-repository@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.PACKAGES_TOKEN }}
      #   with:
      #     source-directory: 'dist'
      #     destination-github-username: ${{ secrets.USE_NAME }}
      #     destination-repository-name: ${{ secrets.REPOSITORY_NAME }}
      #     target-directory: 'dist'
      #     user-email: ${{ secrets.USER_EMAIL }}
      #     target-branch: ${{ secrets.BUILD_BRANCH }}