name: blog DEPLOY CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  publish_packages_job:
    runs-on: ubuntu-latest
    name: build
    steps:
      # check out the repository
      - name: Checkout    
        uses: actions/checkout@v2

      - name: Install and Build 
        run: yarn

      - name: get fetch
        run: npm run fetch

      - name: generate
        run: npm run generate

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PACKAGES_TOKEN }}
        with:
          source-directory: 'src'
          destination-github-username:  'databendcloud'
          destination-repository-name: 'databend-icons'
          target-directory: '.'
          user-email: 'chasenzh@gmail.com'
          target-branch: package
      # - name: login npm 
      #   uses: ahmadnassri/action-github-registry-npm-proxy@v2
      #   with:
      #     token: ${{ secrets.PACKAGES_TOKEN }}
      #     scope: databendcloud
      
      # - name: release
      #   run: npm run release
      
