name: blog DEPLOY CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  publish_packages_job:
    runs-on: ubuntu-latest
    name: build
    steps:
      # check out the repository
      - name: Checkout    
        uses: actions/checkout@v2

      - name: Install and Build 
        run: yarn

      - name: get fetch
        run: npm run fetch

      - name: generate
        run: npm run generate
      
      # - name: login npm 
      #   uses: ahmadnassri/action-github-registry-npm-proxy@v2
      #   with:
      #     token: ${{ secrets.PACKAGES_TOKEN }}
      #     scope: databendcloud
      
      # - name: release
      #   run: npm run release
      
