name: blog DEPLOY CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  publish_packages_job:
    runs-on: ubuntu-latest
    name: build
    steps:
      # check out the repository
      - name: Checkout    
        uses: actions/checkout@v2

      - name: Install and Build 
        run: yarn

      - name: get fetch
        run: npm run fetch

      - name: generate
        run: npm run generate
      
      - name: login npm 
        uses: JS-DevTools/npm-publish@v1
        with:
          usename: chasen-zhange
          email: chasenzh@gmail.com
          token: ${{ secrets.PACKAGES_TOKEN }}
          registry: https://npm.pkg.github.com
      - name: release
        run: npm run release
      
