name: blog DEPLOY CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  publish_packages_job:
    runs-on: ubuntu-latest
    name: build
    steps:
      # check out the repository
      - name: Checkout    
        uses: actions/checkout@v2

      - name: Install and Build 
        run: yarn

      - name: get fetch
        run: npm run fetch

      - name: generate
        run: |
          npm run generate
          npm run build:bundle

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PACKAGES_TOKEN }}
        with:
          source-directory: 'dist'
          destination-github-username: ${{ secrets.USE_NAME }}
          destination-repository-name: ${{ secrets.REPOSITORY_NAME }}
          target-directory: 'dist'
          user-email: ${{ secrets.USER_EMAIL }}
          target-branch: ${{ secrets.BUILD_BRANCH }}
      
      - name: Pushes package.json another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PACKAGES_TOKEN }}
        with:
          source-directory: 'package.json'
          destination-github-username: ${{ secrets.USE_NAME }}
          destination-repository-name: ${{ secrets.REPOSITORY_NAME }}
          target-directory: 'package.json'
          user-email: ${{ secrets.USER_EMAIL }}
          target-branch: ${{ secrets.BUILD_BRANCH }}
      # - name: login npm 
      #   uses: ahmadnassri/action-github-registry-npm-proxy@v2
      #   with:
      #     token: ${{ secrets.PACKAGES_TOKEN }}
      #     scope: databendcloud
      
      # - name: release
      #   run: npm run release
      
